version: "3.8"

services:
  travas-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    # environment:
    #   #Fixes bug where websocket connection is fixed to default port 3000
    #   - WDS_SOCKET_PORT=0

  travas-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    # volumes:
    # - ./server:/app
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
